### ISSUE TITLE
Weather.tingapp

### ISSUE THREAD

**Issue by monglet** [WhistleMaster/tingbot-apps#3]
This does need some setup: line 19:

`state['location'] = 'UKXX0115' `

Needs editing for the location you're in: this can be easily obtained by searching on www.weather.com for your locale and finding the ABCD1234 code from the resulting URL.

**Comment by WhistleMaster** [comment]
You're right ! I'll change that to use tingbot.app.settings.

**Comment by monglet** [comment]
I did wonder when the forecast was for snow all week! Joyous rainy Britain...

**Comment by WhistleMaster** [comment]
Fixed in v1.1.1 [d87d1a0](https://github.com/WhistleMaster/tingbot-apps/commit/d87d1a038315f62b56b09c36e45b393b3d1ca016)
